import type { DirectorProfile, GenreProfile, OutputAdapter, PipelineConfig, RulePack } from "./types";

export const defaultGenreProfiles: GenreProfile[] = [
  {
    id: "urban-emotional",
    name: "都市情感短剧",
    description: "关系冲突、现实压力、情绪爆点驱动。",
    priorities: ["人物关系清晰", "情绪推进明确", "道具信息揭露有节奏"],
  },
  {
    id: "suspense",
    name: "悬疑反转",
    description: "信息差、误导、证据链和反转驱动。",
    priorities: ["隐藏关键信息", "控制揭露顺序", "保持道具状态严谨"],
  },
];

export const defaultDirectorProfiles: DirectorProfile[] = [
  {
    id: "fast-conflict",
    name: "强冲突快节奏",
    description: "高密度情绪和快速信息推进。",
    shotLanguage: ["短镜头", "近景反应", "关键道具特写", "情绪爆点前后拆镜"],
  },
  {
    id: "realistic-calm",
    name: "冷静写实",
    description: "克制镜头、空间关系和自然表演。",
    shotLanguage: ["稳定机位", "中景空间", "自然光", "少量特写"],
  },
];

export const defaultRulePacks: RulePack[] = [
  {
    id: "script-cleaning-v1",
    name: "剧本清洗规则 v1",
    description: "格式清洗、对白格式、集/场标记识别。",
    appliesTo: ["clean_script"],
    rules: ["统一换行和空格", "角色对白使用中文冒号", "保留原文语义不重写剧情"],
  },
  {
    id: "support-pack-v1",
    name: "跨段辅助规则 v1",
    description: "只保留 06/07 当前执行边界看不到、但会影响判断的信息。",
    appliesTo: ["build_episode_support", "plan_scene_context"],
    rules: ["不重复当前块明示信息", "只输出大尺度约束和倾向", "每条辅助信息必须说明用途和可靠性"],
  },
  {
    id: "short-drama-shot-v1",
    name: "短剧分镜规则 v1",
    description: "面向短剧节奏的分镜生成规则。",
    appliesTo: ["plan_scene_storyboard", "generate_block_shots"],
    rules: ["首次按场规划空间和连续性", "局部重跑按块执行", "长对白需拆分或标记复核"],
  },
  {
    id: "prompt-export-v1",
    name: "提示词与导出规则 v1",
    description: "生成视频提示词和标准交付文件。",
    appliesTo: ["build_prompts", "export"],
    rules: ["提示词包含资产连续性", "导出 assets/shots/prompts/grouped csv", "真源优先于派生文件"],
  },
];

export const defaultOutputAdapters: OutputAdapter[] = [
  {
    id: "standard-json-csv",
    name: "标准 JSON + CSV",
    description: "当前默认交付格式。",
    files: ["assets.json", "shots.json", "prompts.json", "EPxx_grouped_prompts.csv"],
  },
  {
    id: "image-prompt-pack",
    name: "资产生图提示词包",
    description: "面向图片生成工作台的资产提示词导出。",
    files: ["asset_image_prompts.json", "locked_assets.json"],
  },
];

export const defaultPipelineConfig: PipelineConfig = {
  id: "short-drama-default-v1",
  name: "短剧默认流程 v1",
  inputMode: "full_series_script",
  genreProfileId: "urban-emotional",
  directorProfileId: "fast-conflict",
  rulePackIds: ["script-cleaning-v1", "support-pack-v1", "short-drama-shot-v1", "prompt-export-v1"],
  outputAdapterId: "standard-json-csv",
  stages: [
    {
      id: "clean_script",
      name: "剧本清洗",
      description: "生成清洗稿和审校疑点。",
      granularity: "project",
      artifactRole: "support",
      purpose: "确保后续 LLM 使用的剧本源头可靠。",
      inputRefs: ["raw_script"],
      outputRefs: ["cleaned_script", "script_issues"],
      executor: "llm",
      status: "done",
      dependencies: [],
    },
    {
      id: "segment_script",
      name: "分集分场分块",
      description: "将长剧本拆成集、场和块级执行单元。",
      granularity: "project",
      artifactRole: "support",
      purpose: "建立长文本处理边界，支持场级首次规划和块级局部重跑；不负责识别资产。",
      inputRefs: ["cleaned_script"],
      outputRefs: ["episodes", "scenes", "blocks"],
      executor: "rule",
      status: "ready",
      dependencies: ["clean_script"],
    },
    {
      id: "build_episode_support",
      name: "集级辅助信息",
      description: "提取一集尺度上 06/07 当前块看不到但必须遵守的信息。",
      granularity: "episode",
      artifactRole: "support",
      purpose: "为场级分镜提供信息揭露顺序、情绪弧线、关系背景、视觉策略等大尺度约束。",
      inputRefs: ["episodes", "genre_profile", "director_profile", "rule_packs"],
      outputRefs: ["episode_support"],
      executor: "llm",
      status: "blocked",
      dependencies: ["segment_script"],
      lockPolicy: "人工确认后锁定；块级重跑不得修改。",
      rerunScopes: ["episode"],
    },
    {
      id: "plan_scene_context",
      name: "场级上下文规划",
      description: "基于整场戏建立场次目的、人物进出、道具流转和空间连续性。",
      granularity: "scene",
      artifactRole: "support",
      purpose: "为场级分镜和块级重跑提供可靠的场内连续性边界。",
      inputRefs: ["scene_script", "episode_support", "rule_packs"],
      outputRefs: ["scene_context", "scene_spatial_timeline", "scene_continuity_notes"],
      executor: "llm",
      status: "blocked",
      dependencies: ["build_episode_support"],
      lockPolicy: "影响空间、人物进出、道具流转时需场级重跑。",
      rerunScopes: ["scene"],
    },
    {
      id: "extract_asset_prompts",
      name: "资产描述与生图提示词",
      description: "生成最终资产描述和资产生图提示词。",
      granularity: "episode",
      artifactRole: "final",
      purpose: "产出最终资产描述/提示词，并供资产生图与视频提示词复用。",
      inputRefs: ["episodes", "episode_support", "scene_context"],
      outputRefs: ["assets", "asset_image_prompts"],
      executor: "llm",
      status: "blocked",
      dependencies: ["build_episode_support", "plan_scene_context"],
      lockPolicy: "资产图锁定后，分镜和提示词不得改写资产外观。",
      rerunScopes: ["episode", "scene"],
    },
    {
      id: "plan_scene_storyboard",
      name: "场级分镜规划",
      description: "以整场戏为边界生成分镜规划和场内空间时序。",
      granularity: "scene",
      artifactRole: "final",
      purpose: "首次生成时建立视听设计、镜头拆分、空间站位和连续性。",
      inputRefs: ["scene_script", "episode_support", "scene_context", "assets", "locked_assets"],
      outputRefs: ["scene_storyboard_plan", "scene_spatial_timeline", "scene_shot_ranges"],
      executor: "llm",
      status: "blocked",
      dependencies: ["plan_scene_context", "extract_asset_prompts"],
      lockPolicy: "场级空间时序确认后，块级重跑只能引用不得改写。",
      rerunScopes: ["scene"],
    },
    {
      id: "generate_block_shots",
      name: "块级分镜执行",
      description: "在锁定的集级/场级状态下，对单块镜头做生成或局部重生成。",
      granularity: "block",
      artifactRole: "final",
      purpose: "降低长文本成本，支持人工不满意时局部重跑。",
      inputRefs: ["block_script", "episode_support", "scene_context", "scene_spatial_timeline", "locked_assets", "neighboring_shots"],
      outputRefs: ["shots"],
      executor: "llm",
      status: "blocked",
      dependencies: ["plan_scene_storyboard"],
      lockPolicy: "必须遵守 episode_support、scene_context、scene_spatial_timeline、locked_assets。",
      rerunScopes: ["block"],
    },
    {
      id: "build_video_prompts",
      name: "视频提示词",
      description: "基于具体镜头、锁定资产和场内空间时序生成视频提示词。",
      granularity: "shot",
      artifactRole: "final",
      purpose: "产出最终视频提示词，并保持资产、空间、情绪和道具连续。",
      inputRefs: ["shots", "scene_spatial_timeline", "locked_assets", "style_profile"],
      outputRefs: ["prompts"],
      executor: "llm",
      status: "blocked",
      dependencies: ["generate_block_shots"],
      lockPolicy: "不得发明与锁定资产或空间时序冲突的信息。",
      rerunScopes: ["shot", "block"],
    },
    {
      id: "validate",
      name: "真源校验",
      description: "校验最终产物和必要中间产物的完整性。",
      granularity: "project",
      artifactRole: "validation",
      purpose: "只校验被最终产物引用的信息，避免无效中间产物进入流程。",
      inputRefs: ["assets", "asset_image_prompts", "shots", "prompts", "episode_support", "scene_context"],
      outputRefs: ["validation_report"],
      executor: "rule",
      status: "blocked",
      dependencies: ["build_video_prompts"],
      rerunScopes: ["project", "episode", "scene", "block"],
    },
    {
      id: "export",
      name: "交付导出",
      description: "按输出适配器生成交付文件。",
      granularity: "export",
      artifactRole: "delivery",
      purpose: "输出资产描述/提示词、分镜规划/视频提示词和交付文件。",
      inputRefs: ["assets", "asset_image_prompts", "shots", "prompts"],
      outputRefs: ["delivery_files"],
      executor: "export",
      status: "blocked",
      dependencies: ["validate"],
      rerunScopes: ["export"],
    },
  ],
};
